/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bitcon;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrés Bolaños
 */
public class Frm_ISWBITCON extends javax.swing.JFrame {
    private Juego Juego_ISWBITCON;
    private Frm_ConfiguracionJuego ConfigForm;

    /**
     * Creates new form Frm_ISWBITCON
     */
    public Frm_ISWBITCON(Frm_ConfiguracionJuego ConfigForm) {
        initComponents();
        
        this.ConfigForm = ConfigForm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_Logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txa_Tablero = new javax.swing.JTextArea();
        Lbl_Tirulo = new javax.swing.JLabel();
        Lbl_CodigoTablero = new javax.swing.JLabel();
        Txf_CodigoTablero = new javax.swing.JTextField();
        Btn_GenerarTableros = new javax.swing.JButton();
        Btn_ImprimirTablero = new javax.swing.JButton();
        Lbl_NombreTablero = new javax.swing.JLabel();
        Txa_ConfiguracionJuego = new javax.swing.JTextArea();
        Lbl_FichaCapturada = new javax.swing.JLabel();
        Txf_FichaCapturada = new javax.swing.JTextField();
        Btn_IngresarFicha = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Txa_TablerosGanadores = new javax.swing.JTextArea();
        Lbl_TablerosGanadores = new javax.swing.JLabel();
        Btn_Salir = new javax.swing.JButton();
        Btn_Reiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Andrés Bolaños Víquez | 1-1909-0051");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Lbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bitcon/logo.png"))); // NOI18N

        Txa_Tablero.setEditable(false);
        Txa_Tablero.setColumns(20);
        Txa_Tablero.setRows(5);
        jScrollPane1.setViewportView(Txa_Tablero);

        Lbl_Tirulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Lbl_Tirulo.setText("ISW | BITCON");

        Lbl_CodigoTablero.setText("Codigo del tablero a Mostrar");

        Txf_CodigoTablero.setText("1000");

        Btn_GenerarTableros.setText("Generar Tableros");
        Btn_GenerarTableros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GenerarTablerosActionPerformed(evt);
            }
        });

        Btn_ImprimirTablero.setText("Mostrar");
        Btn_ImprimirTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ImprimirTableroActionPerformed(evt);
            }
        });

        Lbl_NombreTablero.setText("Nombre del tablero: ");

        Txa_ConfiguracionJuego.setEditable(false);
        Txa_ConfiguracionJuego.setColumns(20);
        Txa_ConfiguracionJuego.setRows(5);
        Txa_ConfiguracionJuego.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuración del juego"));

        Lbl_FichaCapturada.setText("Ficha a capturar");

        Btn_IngresarFicha.setText("Ingresar ficha");
        Btn_IngresarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_IngresarFichaActionPerformed(evt);
            }
        });

        Txa_TablerosGanadores.setEditable(false);
        Txa_TablerosGanadores.setColumns(20);
        Txa_TablerosGanadores.setRows(5);
        jScrollPane2.setViewportView(Txa_TablerosGanadores);

        Lbl_TablerosGanadores.setText("Tableros Ganadores");

        Btn_Salir.setText("Salir");
        Btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalirActionPerformed(evt);
            }
        });

        Btn_Reiniciar.setText("Reiniciar");
        Btn_Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_NombreTablero)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_Salir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Reiniciar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Lbl_FichaCapturada)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Txf_FichaCapturada, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Btn_IngresarFicha)
                                        .addGap(243, 243, 243)
                                        .addComponent(Lbl_TablerosGanadores))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Lbl_Logo)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(Lbl_Tirulo))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Lbl_CodigoTablero)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(Txf_CodigoTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Btn_ImprimirTablero)
                                                .addComponent(Btn_GenerarTableros))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Txa_ConfiguracionJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Lbl_Logo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lbl_Tirulo)
                                    .addComponent(Btn_GenerarTableros))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl_CodigoTablero)
                            .addComponent(Txf_CodigoTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_ImprimirTablero)))
                    .addComponent(Txa_ConfiguracionJuego, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lbl_NombreTablero)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_FichaCapturada)
                    .addComponent(Txf_FichaCapturada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_IngresarFicha)
                    .addComponent(Lbl_TablerosGanadores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn_Salir)
                        .addComponent(Btn_Reiniciar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_GenerarTablerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GenerarTablerosActionPerformed
        // TODO add your handling code here:
        Juego_ISWBITCON = new Juego(Frm_ConfiguracionJuego.sistemaNumerico, Frm_ConfiguracionJuego.TipoTableros);
        
        Txa_ConfiguracionJuego.setText("Generación de fichas: " + Frm_ConfiguracionJuego.GeneracionFichas + "\nSistema numerico: " + Frm_ConfiguracionJuego.SistemaNumericoString + "\nTipo de tablero: " + Frm_ConfiguracionJuego.TipoTablerosString);
        
        Lbl_CodigoTablero.setVisible(true);
        Txf_CodigoTablero.setVisible(true);
        Lbl_NombreTablero.setVisible(true);
        Txa_Tablero.setVisible(true);
        Txa_ConfiguracionJuego.setVisible(true);
        Btn_ImprimirTablero.setVisible(true);
        Lbl_FichaCapturada.setVisible(true);
        Txf_FichaCapturada.setVisible(true);
        Btn_IngresarFicha.setVisible(true);
        Lbl_TablerosGanadores.setVisible(true);
        Txa_TablerosGanadores.setVisible(true);
        
        Btn_GenerarTableros.setVisible(false);
        
        if(Frm_ConfiguracionJuego.GeneracionFichas == "Aleatorio"){
            Txf_FichaCapturada.setEditable(false);
            Txf_FichaCapturada.setText("" + Juego_ISWBITCON.GenerarNumeroDeFichaAleatorio());
        }
        
    }//GEN-LAST:event_Btn_GenerarTablerosActionPerformed

    private int validarCodigoIngresado(String  HileraIngresada){
        try
        {
            if(!HileraIngresada.equals("")){
                int codigoIngresado = Integer.parseInt(HileraIngresada);
                if(1000 <= codigoIngresado && codigoIngresado <= 1100){
                    
                    return codigoIngresado;
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Favor digite un codigo de tablero mayor igual a 1000 y menor igual a 1100.", "Digitar posiciones del tablero reales", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Favor ingresar un codigo de tablero a buscar", "Favor rellenar los campos solicitados", JOptionPane.WARNING_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Favor digitar un formato de dato correspondiente al solicitado", "ERROR de formato", JOptionPane.WARNING_MESSAGE);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ha sucedido un error.\n" + e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        return 0;
    }
    
    private void ImprimirTablero(){
        
        int codigoTablero = validarCodigoIngresado(Txf_CodigoTablero.getText());
        
        if(codigoTablero != 0){
            Tablero tableroSeleccionado = Juego_ISWBITCON.ObtenerTablero(codigoTablero);
        
            if(tableroSeleccionado.isTableroGanador()){
                Txa_Tablero.setForeground(Color.green);
            }else{
                Txa_Tablero.setForeground(Color.black);
            }

            Txa_Tablero.setText(tableroSeleccionado.ImprimirTablero());
            Lbl_NombreTablero.setText("Nombre del tablero: " + tableroSeleccionado.getNombreTablero());
        }
    }
    
    private void Btn_ImprimirTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ImprimirTableroActionPerformed
        // TODO add your handling code here:
        
        ImprimirTablero();
    }//GEN-LAST:event_Btn_ImprimirTableroActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        Lbl_CodigoTablero.setVisible(false);
        Txf_CodigoTablero.setVisible(false);
        Lbl_NombreTablero.setVisible(false);
        Txa_Tablero.setVisible(false);
        Txa_ConfiguracionJuego.setVisible(false);
        Btn_ImprimirTablero.setVisible(false);
        Lbl_FichaCapturada.setVisible(false);
        Txf_FichaCapturada.setVisible(false);
        Btn_IngresarFicha.setVisible(false);
        Lbl_TablerosGanadores.setVisible(false);
        Txa_TablerosGanadores.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private int validarFichaIngresada(String  HileraIngresada){
        try
        {
            if(!HileraIngresada.equals("")){
                int fichaIngresada = Integer.parseInt(HileraIngresada);
                if(1 <= fichaIngresada && fichaIngresada <= 95){
                    
                    return fichaIngresada;
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Numeros de ficha admitidos: mayor igual a 1 y menor igual a 95.", "Digitar valores de fichas reales", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Favor ingresar una ficha a capturar", "Favor rellenar los campos solicitados", JOptionPane.WARNING_MESSAGE);
            }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Favor digitar un formato de dato correspondiente al solicitado", "ERROR de formato", JOptionPane.WARNING_MESSAGE);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ha sucedido un error.\n" + e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        return 0;
    }
    
    private void Btn_IngresarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IngresarFichaActionPerformed
        // TODO add your handling code here:
        int fichaCapturada = validarFichaIngresada(Txf_FichaCapturada.getText());
        
        if(fichaCapturada != 0){
            Juego_ISWBITCON.MarcarTableros(fichaCapturada);
            Txf_FichaCapturada.setText("");
            JOptionPane.showMessageDialog(null, "Ficha #" + fichaCapturada + " marcada en los tableros", "Ficha capturada", JOptionPane.INFORMATION_MESSAGE);
            ImprimirTablero();

            if(!Juego_ISWBITCON.ValidarTableros().equals("")){
                Txa_TablerosGanadores.setText(Juego_ISWBITCON.ValidarTableros());
                ImprimirTablero();
                JOptionPane.showMessageDialog(null, Juego_ISWBITCON.ValidarTableros(), "GANADORES", JOptionPane.INFORMATION_MESSAGE);
                reiniciarJuego();
            }
        }
        
        if(Frm_ConfiguracionJuego.GeneracionFichas == "Aleatorio"){
            Txf_FichaCapturada.setText("" + Juego_ISWBITCON.GenerarNumeroDeFichaAleatorio());
        }
    }//GEN-LAST:event_Btn_IngresarFichaActionPerformed

    private void Btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalirActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
        
    }//GEN-LAST:event_Btn_SalirActionPerformed

    private void Btn_ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ReiniciarActionPerformed
        // TODO add your handling code here:
        
        reiniciarJuego();
        
    }//GEN-LAST:event_Btn_ReiniciarActionPerformed

    
    private void reiniciarJuego(){
        ConfigForm.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_ISWBITCON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_ISWBITCON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_ISWBITCON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_ISWBITCON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                return;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_GenerarTableros;
    private javax.swing.JButton Btn_ImprimirTablero;
    private javax.swing.JButton Btn_IngresarFicha;
    private javax.swing.JButton Btn_Reiniciar;
    private javax.swing.JButton Btn_Salir;
    private javax.swing.JLabel Lbl_CodigoTablero;
    private javax.swing.JLabel Lbl_FichaCapturada;
    private javax.swing.JLabel Lbl_Logo;
    private javax.swing.JLabel Lbl_NombreTablero;
    private javax.swing.JLabel Lbl_TablerosGanadores;
    private javax.swing.JLabel Lbl_Tirulo;
    private javax.swing.JTextArea Txa_ConfiguracionJuego;
    private javax.swing.JTextArea Txa_Tablero;
    private javax.swing.JTextArea Txa_TablerosGanadores;
    private javax.swing.JTextField Txf_CodigoTablero;
    private javax.swing.JTextField Txf_FichaCapturada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
