/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bitcon;

import javax.swing.JOptionPane;

/**
 *
 * @author Andrés Bolaños
 */
public class Frm_ConfiguracionJuego extends javax.swing.JFrame {
    
    public static String GeneracionFichas;
    public static int sistemaNumerico;
    public static String SistemaNumericoString;
    public static int TipoTableros;
    public static String TipoTablerosString;
    
    /**
     * Creates new form Frm_ConfiguracionJuego
     */
    public Frm_ConfiguracionJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_WhiteLogo = new javax.swing.JLabel();
        jPanel_Configuracion = new javax.swing.JPanel();
        Lbl_GeneracionFichas = new javax.swing.JLabel();
        Cmb_GeneracionFichas = new javax.swing.JComboBox<>();
        Lbl_SistemaNumerico = new javax.swing.JLabel();
        Cmb_SistemaNumerico = new javax.swing.JComboBox<>();
        Lbl_TiposTableros = new javax.swing.JLabel();
        Cmb_TipoTableros = new javax.swing.JComboBox<>();
        Btn_IniciarJuego = new javax.swing.JButton();
        Btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Andrés Bolaños Víquez | 1-1909-0051");
        setResizable(false);

        Lbl_WhiteLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bitcon/White_Logo.png"))); // NOI18N

        jPanel_Configuracion.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuración del juego"));

        Lbl_GeneracionFichas.setText("Generación de Fichas");

        Cmb_GeneracionFichas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aleatorio", "Manual" }));

        Lbl_SistemaNumerico.setText("Sistema Numerico");

        Cmb_SistemaNumerico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quinario", "Octal", "Decimal", "Duodecimal", "Hexadecimal" }));

        Lbl_TiposTableros.setText("Tipo de tablero a jugar");

        Cmb_TipoTableros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Linea horizontal", "Linea vertical", "Linea diagonal" }));

        javax.swing.GroupLayout jPanel_ConfiguracionLayout = new javax.swing.GroupLayout(jPanel_Configuracion);
        jPanel_Configuracion.setLayout(jPanel_ConfiguracionLayout);
        jPanel_ConfiguracionLayout.setHorizontalGroup(
            jPanel_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ConfiguracionLayout.createSequentialGroup()
                        .addGroup(jPanel_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_GeneracionFichas)
                            .addComponent(Lbl_SistemaNumerico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cmb_GeneracionFichas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cmb_SistemaNumerico, 0, 106, Short.MAX_VALUE)))
                    .addGroup(jPanel_ConfiguracionLayout.createSequentialGroup()
                        .addComponent(Lbl_TiposTableros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cmb_TipoTableros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel_ConfiguracionLayout.setVerticalGroup(
            jPanel_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConfiguracionLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_GeneracionFichas)
                    .addComponent(Cmb_GeneracionFichas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_SistemaNumerico)
                    .addComponent(Cmb_SistemaNumerico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_TiposTableros)
                    .addComponent(Cmb_TipoTableros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Btn_IniciarJuego.setText("Iniciar Juego");
        Btn_IniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_IniciarJuegoActionPerformed(evt);
            }
        });

        Btn_Salir.setText("Salir");
        Btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_Salir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_IniciarJuego)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(Lbl_WhiteLogo)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Lbl_WhiteLogo)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Salir)
                    .addComponent(Btn_IniciarJuego))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Btn_SalirActionPerformed

    private void Btn_IniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IniciarJuegoActionPerformed
        // TODO add your handling code here:
        
        GeneracionFichas = Cmb_GeneracionFichas.getSelectedItem().toString();
        sistemaNumerico = Cmb_SistemaNumerico.getSelectedIndex();
        SistemaNumericoString = Cmb_SistemaNumerico.getSelectedItem().toString();
        TipoTableros = Cmb_TipoTableros.getSelectedIndex();
        TipoTablerosString = Cmb_TipoTableros.getSelectedItem().toString();
        

        Frm_ISWBITCON formularioJuego = new Frm_ISWBITCON(this);

        formularioJuego.setVisible(true);
        this.setVisible(false);
        
        Cmb_GeneracionFichas.setSelectedIndex(0);
        Cmb_SistemaNumerico.setSelectedIndex(0);
        Cmb_TipoTableros.setSelectedIndex(0);
    }//GEN-LAST:event_Btn_IniciarJuegoActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_ConfiguracionJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_ConfiguracionJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_ConfiguracionJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_ConfiguracionJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_ConfiguracionJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_IniciarJuego;
    private javax.swing.JButton Btn_Salir;
    private javax.swing.JComboBox<String> Cmb_GeneracionFichas;
    private javax.swing.JComboBox<String> Cmb_SistemaNumerico;
    private javax.swing.JComboBox<String> Cmb_TipoTableros;
    private javax.swing.JLabel Lbl_GeneracionFichas;
    private javax.swing.JLabel Lbl_SistemaNumerico;
    private javax.swing.JLabel Lbl_TiposTableros;
    private javax.swing.JLabel Lbl_WhiteLogo;
    private javax.swing.JPanel jPanel_Configuracion;
    // End of variables declaration//GEN-END:variables
}
